# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-02 09:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20160702_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='viewCount',
            field=models.IntegerField(default=0),
        ),
    ]
