# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-02 09:33
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20160702_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='datePublished',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='articles',
            name='title',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
