# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-05 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='writer',
            field=models.CharField(default=0, max_length=150),
            preserve_default=False,
        ),
    ]
