# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-05 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_comments_writer'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='subtitle',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
