# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-05 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_articles_subtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='url',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
