# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-05 16:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_articles_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='title',
            field=models.TextField(),
        ),
    ]
