# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-05 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0011_auto_20160705_2129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='url',
        ),
        migrations.AddField(
            model_name='articles',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
