# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-03 07:00
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageTitle', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('title', models.TextField()),
                ('subtitle', models.TextField()),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('datePublished', models.CharField(blank=True, max_length=11, null=True)),
                ('viewCount', models.IntegerField(default=0)),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'News',
                'verbose_name_plural': 'News',
            },
        ),
    ]
