# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-03 06:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='url',
            field=models.CharField(default='/', max_length=200),
        ),
    ]
