# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-03 06:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventa', '0003_event_eventimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='fadate',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
